### ISSUE TITLE
Toggle only working once!

### ISSUE THREAD

**Issue by kueblertgb** [gitbrent/bootstrap4-toggle#10]
Hi,
i am Using Jquery 3.4.1
and Bootsrap 4.3.1
and Bootsrap-Toggle 3.5.0

The Toggle button code is
`<input id="chkToggle1" type="checkbox" data-toggle="toggle" checked>`

In Dev-Mode in Crome it is shown as

`<div class="toggle btn btn-primary" data-toggle="toggle" role="button" style="width: 61.0781px; height: 38px;">

    <div class="toggle btn btn-primary" data-toggle="toggle" role="button" style="width: 61.0781px; height: 38px;">
    	<input id="chkToggle1" type="checkbox" data-toggle="toggle" checked="">
        <div class="toggle-group">
            <label class="btn btn-primary toggle-on">On</label>
            <label class="btn btn-light toggle-off">Off</label>
            <span class="toggle-handle btn btn-light"></span>
        </div>
    </div>

    <div class="toggle-group">
        <label class="btn btn-primary toggle-on">On</label>
        <label class="btn btn-light toggle-off">Off</label>
        <span class="toggle-handle btn btn-light"></span>
    </div>

</div>`

The first div statement is shown 2 times:
<div class="toggle btn btn-primary" data-toggle="toggle" role="button" style="width: 61.0781px; height: 38px;">

maybe that is the reason wy it is not function

**Comment by kueblertgb** [comment]
here the first line is not shown 2 times..
this editor here seams to filter the second div statement beacuse it is double...maybe...

**Comment by kueblertgb** [comment]
no help here? comone...plz..

**Comment by gitbrent** [comment]
I'm unsure what the issue is.

There are lots of [working demos available](https://gitbrent.github.io/bootstrap4-toggle/) you can use to model code from.
