### ISSUE TITLE
not working with mdbootstrap

### ISSUE THREAD

**Issue by lutfisan** [gitbrent/bootstrap4-toggle#12]
I try this code with mdbootstrap
`<input type="checkbox" checked data-toggle="toggle" data-on="Ready" data-off="Not Ready" data-onstyle="success" data-offstyle="danger">
`
![image](https://user-images.githubusercontent.com/29010489/64333175-39371780-d000-11e9-914b-f768518b2acf.png)

**Comment by gitbrent** [comment]
Hi @lutfisan 

The library was not designed with mdbootstrap in mind.  They may be incompatible..?
