### ISSUE TITLE
Disable style is not working

### ISSUE THREAD

**Issue by rychlym** [gitbrent/bootstrap4-toggle#18]
Hello!

It looks the calling disable does not have any visual effect, so it seems the something is wrong with the styling.  Not working also on the demo - https://gitbrent.github.io/bootstrap4-toggle 

Any clue how to fix it?

**Comment by gitbrent** [comment]
Hi @rychlym 

Thanks for reporting this.  I've copied the disabled style from the ES6 version and it looks correct now.

Enabled:
<img width="562" alt="Screen Shot 2019-10-09 at 21 38 35" src="https://user-images.githubusercontent.com/7218970/66534921-697d4480-eadd-11e9-904d-270d35850d6a.png">

Disabled:
<img width="561" alt="Screen Shot 2019-10-09 at 21 38 45" src="https://user-images.githubusercontent.com/7218970/66534920-697d4480-eadd-11e9-8bc5-c8439f7d0146.png">

**Comment by rychlym** [comment]
Hi @gitbrent,

Please excuse me for a kind newbie  question - I have seen your change (handling the disable class), but I am not sure it is released already? (The demo seems still not working)... So what to do to get the  fixed version in the near future days?
