### ISSUE TITLE
Mobile Touch does not work with 4.3.1

### ISSUE THREAD

**Issue by wilecoyte78** [gitbrent/bootstrap4-toggle#2]
When on mobile devices the toggle does not toggle.

**Comment by rafaelstreitoe** [comment]
It works fine on Android devices, but it isn't working on iOS.
I found a workaround to make it work, add `cursor: pointer;` to the `div` that has the listener.
See the example below that I used.
```
div[data-toggle^=toggle] {
    cursor: pointer;
}
```
https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event#Safari_Mobile

**Comment by gitbrent** [comment]
@wilecoyte78 @rafaelstreitoe - how are you testing this?

I have the [demo site](https://gitbrent.github.io/bootstrap4-toggle/) open on an iPhone running iOS 12 and all the toggles work fine...?

**Comment by Kholodny** [comment]
> @wilecoyte78 @rafaelstreitoe - how are you testing this?
> 
> I have the [demo site](https://gitbrent.github.io/bootstrap4-toggle/) open on an iPhone running iOS 12 and all the toggles work fine...?

this issue is reproduced on bootstrap 4.3.1

2 ways to fix:
1. .btn {cursor: pointer!important;} in bootstrap-toggle.min.css
2. change touch event in bootstrap-toggle.min.js to touchstart

**Comment by wilecoyte78** [comment]
> > @wilecoyte78 @rafaelstreitoe - how are you testing this?
> > I have the [demo site](https://gitbrent.github.io/bootstrap4-toggle/) open on an iPhone running iOS 12 and all the toggles work fine...?
> 
> this issue is reproduced on bootstrap 4.3.1
> 
> 2 ways to fix:
> 
> 1. .btn {cursor: pointer!important;} in bootstrap-toggle.min.css
> 2. change touch event in bootstrap-toggle.min.js to touchstart

I tested and confirmed the two changes do work. However you do not need to do but is good to have so you see that it is clickable. Also do not have to have !important unless there is another definition that has !important

**Comment by gitbrent** [comment]
@Kholodny  - Dang, so `4.3.1` did break touch events!

@wilecoyte78 @Kholodny 
* I've updated the demo site to BS 4.3.1 and updated the touch events
* Please see if the touch events are working for you now

Thanks!

**Comment by wilecoyte78** [comment]
@gitbrent The events work on your demo site on iPhone 8 Plus iOS 12.3.2

**Comment by gitbrent** [comment]
@wilecoyte78 - thanks for testing

**Comment by gitbrent** [comment]
I've also added `cursor:pointer` to the toggle class, plus an additional ARIA tag (`role="button"`)

**Comment by gitbrent** [comment]
#
