### ISSUE TITLE
The 'change' event will be triggered when the page loaded

### ISSUE THREAD

**Issue by KarlWang** [gitbrent/bootstrap4-toggle#3]
Hi,

I found that the 'change' event of toggle will be triggered every time the page gets loaded.
Is there a way to stop that?

Thanks!

**Comment by KarlWang** [comment]
I updated to the latest version then double checked my code. All good now.

**Comment by gitbrent** [comment]
Good to hear!

**Comment by KarlWang** [comment]
Sorry probably I should've described it more clearly: 

On my page, I set up initial status for the toggle, using
`$('#toggle-demo').bootstrapToggle('on')`
or 
`$('#toggle-demo').bootstrapToggle('off')`

But that would trigger the 'change' event, which was not what I expected.

Cheers
Karl

**Comment by gitbrent** [comment]
Yes, I see what you mean. In this case the code was behaving as intended.
