### ISSUE TITLE
Styles are not applied to dynamically generated toggle buttons 

### ISSUE THREAD

**Issue by Anushadokuparthi** [gitbrent/bootstrap4-toggle#6]
Hello,

I am trying to generate maximum  number of 5 toggle buttons dynamically form jquery script when user clicks on add button. Instead of toggle buttons plain checkboxes were displayed. Can anyone help me to solve this issue and I would like to know how to give unique id for each of this toggle button.

Thanks in advance :)

 

>Note: .insurance-check-form is the div tag where dynamic buttons are added

![Capture1](https://user-images.githubusercontent.com/43666166/62105537-4dc91700-b2c0-11e9-83bc-53ef66c8df73.PNG)

`  <script>
          $(document).ready(function(){
         
         var max_fields = 5;
         var field_wrapper = $(".insurance-check-form");       
         var add_button = $("#add-more");
         var ins_company_count = 1;

         $(document).on("click","#add-more",(function(e){
             e.preventDefault();
             if(ins_company_count < max_fields){
                 $(field_wrapper).append('<div class="row mt-5"> <div class="col-md-2"> <select name="insurance" class="custom-select"> <option selected>Custom Select Menu</option> <option value="volvo">ICCI Prudential</option> <option value="fiat">Blue Star</option> <option value="audi">Edelwiss Tokyo</option> </select> </div><div class="col-md-3"> <input type="checkbox" data-toggle="toggle" data-style="slow" data-width="250" data-height="35" data-on="Click to Unsubmit" data-off="Click to Submit" data-onstyle="primary" data-offstyle="secondary" id="clearance-check"><br><span class="head3" data-toggle="popover" data-trigger="hover" data-content="Click here to add a notes"> <button class="btn btn-link" data-toggle="modal" data-target="#igl-sub-modal" data-backdrop="static" data-keyboard="false"> <i class="far fa-file-alt head3 text-gray"></i></button> </div><div class="col-md-3"> <input type="checkbox" data-toggle="toggle" data-style="slow" data-width="250" data-height="35" data-on="Click to Unsubmit" data-off="Click to Submit" data-onstyle="primary" data-offstyle="secondary" id="clearance-check"><br><span class="head3" data-toggle="popover" data-trigger="hover" data-content="Click here to add a notes"> <button class="btn btn-link" data-toggle="modal" data-target="#igl-sub-modal" data-backdrop="static" data-keyboard="false"> <i class="far fa-file-alt head3 text-gray"></i></button> </div><div class="col-md-3"> <input type="checkbox" data-toggle="toggle" data-style="slow" data-width="250" data-height="35" data-on="Click to Unsubmit" data-off="Click to Submit" data-onstyle="primary" data-offstyle="secondary" id="clearance-check"><br><span class="head3" data-toggle="popover" data-trigger="hover" data-content="Click here to add a notes"> <button class="btn btn-link" data-toggle="modal" data-target="#igl-sub-modal" data-backdrop="static" data-keyboard="false"> <i class="far fa-file-alt head3 text-gray"></i></button> </div><a href="#" class="remove_field"><i class="fas fa-times-circle brand-color head2"></i></a></div>');
                  ins_company_count++;
                  $('head').append(' <link href="../assets/libs/css/bootstrap4-toggle.min.css" rel="stylesheet">');
                 
             }
         }))
{)`

**Comment by zacharynanfelt** [comment]
@Anushadokuparthi it looks like you can simply use the following code to enable the feature on dynamically generated elements:

`$("#new-object").bootstrapToggle();`

https://stackoverflow.com/questions/32586384/bootstrap-toggle-doesnt-work-after-ajax-load

**Comment by gitbrent** [comment]
@Anushadokuparthi - @zacharynanfelt is correct, checkboxes added after the page has loaded need to be initialized.

See "Usage" [API Docs](https://gitbrent.github.io/bootstrap4-toggle/)

```
<input id="chkToggle2" type="checkbox" checked>
<script>
  $(function(){ $('#chkToggle2').bootstrapToggle() });
</script>
```
