### ISSUE TITLE
Silent API

### ISSUE THREAD

**Issue by aswin1980** [gitbrent/bootstrap4-toggle#7]
Hi,
I have gone through the code and in order to not trigger change event and set silent this is what we have done.
```javascript
 var bs = $(company).bootstrapToggle().data('bs.toggle');
 bs.on(true);
```
is this correct?
Is there a better way to do it?
something like
```javascript
$('#toggle-demo').bootstrapToggle('on,silent')
```

The use case is I ask the user a question in an alert to answer yes or no in JS change event when the toggle the checkbox. If the user answers no I should go back to the original state and not trigger the change.

Appreciate if this can be added to your API document

Thanks
Aswin

**Comment by gitbrent** [comment]
Hi @aswin1980 

Thanks for the issue.

Support for silent toggle has been added and included in `index.html` demo.

Regular toggle:
```javascript
$('#toggle-demo').bootstrapToggle('on')
```
Silent toggle (does not trigger `onChange` event):
```javascript
$('#toggle-demo').bootstrapToggle('on', true)
```

**Comment by aswin1980** [comment]
Thanks
